#!/usr/bin/env bash
# installs nginx and changes default html to return "Hello World!"
apt install nginx -y
echo "Hello World!" > ~/index.html
chmod a+w /etc/nginx/sites-enabled/default
old_root="root /var/www/html;"
new_root="# root /var/www/html;\n\troot /home/ubuntu;"
sed -i "s+$old_root+$new_root+" /etc/nginx/sites-enabled/default
nginx -s reload