#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update -y
# sudo apt-get install --no-install-recommends software-properties-common -y
# sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "
frontend haproxy-main
    bind *:80
    mode http
    default_backend webservers" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "backend webservers
    balance roundrobin
    option forwardfor
    server web-01  54.234.160.185:80 check
    server web-02  3.91.201.90:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart